### ISSUE TITLE
[clang] additional arches

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#105]
we should be able to build arm64, arm, x86_64, ppc32le, and ppc64le with clang-9.

**Comment by broonie** [comment]
Given that clang-9 is still in development we would first need to work out handing for in development compilers properly, we don't want instability in the compiler bothering people who don't care about that - that was never really handled, we just left the builds on staging.

PowerPC would be a new architecture for which we have no physical hardware - someone else did raise on the list the idea of covering as many qemuable architectures as possible so that would fit into that. 64 bit PowerPC does have the issue that the Debian port is questionable (it's never been a release architecture, very low demand), unless it can boot 32 bit userspace in which case we could just use the 32 bit port for boot testing.

**Comment by nickdesaulniers** [comment]
> Given that clang-9 is still in development we would first need to work out handing for in development compilers properly

So there seems to be a docker image for clang-9: https://github.com/kernelci/kernelci-core/blob/dd1747b4ae595cefbc6fa23b7187fd1d7f4ca170/jenkins/dockerfiles/clang-9/Dockerfile

I'm not sure how often that gets rebuilt?  I assume it would have to be rebuilt daily to repackage the latest development build of clang.

> we don't want instability in the compiler bothering people who don't care about that - that was never really handled, we just left the builds on staging.

Yes; but I care about that and need the emails/bugreports.  So maybe we never email kernel devs about build breakages w/ pre-release compilers, but maybe we can just email clang-built-linux@googlegroups.com for build breakages w/ pre-release versions of clang?

**Comment by gctucker** [comment]
> > Given that clang-9 is still in development we would first need to work out handing for in development compilers properly
> 
> So there seems to be a docker image for clang-9: https://github.com/kernelci/kernelci-core/blob/dd1747b4ae595cefbc6fa23b7187fd1d7f4ca170/jenkins/dockerfiles/clang-9/Dockerfile
> 
> I'm not sure how often that gets rebuilt? I assume it would have to be rebuilt daily to repackage the latest development build of clang.

It's rebuilt when kernelci.org is being updated, so typically every Friday.

You can see in the build details the exact version that was used, with the string returned by the clang binary:
https://kernelci.org/build/id/5d2c2d4659b514346149e933/

And here's the Dockerfile, with the details of where it gets the packages from:
https://github.com/kernelci/kernelci-core/blob/master/jenkins/dockerfiles/clang-9/Dockerfile
