### ISSUE TITLE
LLVM=1 support

### ISSUE THREAD

**Issue by nickdesaulniers** [kernelci/kernelci-core#491]
I think @khilman and @gctucker already have this working, but just wanted to file a bug to track this work if there's not one already.  Please close if this is all set.  I'm not sure if there's any reporting infrastructure/emails/web ui that needs to be changed from CC=clang to LLVM=1, perhaps?

**Comment by gctucker** [comment]
Yes it's all merged, and should be deployed in production tomorrow.  The web UI and email reports aren't impacted, it's still just considered "clang builds".  The only visible difference there will be in the build log which includes the full make commands.

This also fixed the calls to `merge_config.sh` because the `LLVM` variable can be derived from the environment with no default hard-coded value in the top-level `Makefile` unlike `CC` etc...  So now we're starting to see things like big-endian clang builds.

Maybe you can wait until you get some linux-next build results tomorrow or Monday with clang-10 that used LLVM=1 and then close this issue to confirm it's all looking OK?

**Comment by gctucker** [comment]
Here's a sample arm64 clang-10 build job on linux-next:
https://kernelci.org/build/id/5f5f45012ce3eebb49a60919/

Build log and make command:
https://storage.kernelci.org/next/master/next-20200914/arm64/defconfig/clang-10/build.log
```
make KBUILD_BUILD_USER=KernelCI -C/scratch/linux -j18 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabihf- LLVM=1 CC="ccache clang" O=/root/build Image
```
So this seems all fine to me.

There is an issue with clang-9 but that's because it appears to now be too old for building linux-next: #496 

@nickdesaulniers Please confirm and close this issue.

**Comment by nickdesaulniers** [comment]
[x86](https://storage.kernelci.org/next/master/next-20200914/x86_64/x86_64_defconfig/clang-10/build.log)
[arm](https://storage.kernelci.org/next/master/next-20200914/arm/multi_v7_defconfig/clang-10/build.log)

LGTM thanks! 🇲🇭 🧇
