### ISSUE TITLE
Power supplies test coverage

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#669]
This is about enabling tests for the power supply subsystem and drivers in KernelCI.  Tests may be added to KUnit, Kselftest or as a stand-alone user-space.

There is a test driver which can be used to emulate a power supply, this can even be used with QEMU:
`drivers/power/supply/test_power.c`, enabled with `CONFIG_TEST_POWER`

Note: Enabling it would require a config fragment so extra kernel builds, unless it's grouped with other similar test configs that don't interfere with each other.

This driver was created in the early days of the subsystem and may need to be improved.

Other tests should also be run on real hardware, at least to check the presence of the power supplies and functional tests if possible although this might require extra hardware.

- [ ] #699 investigation

**Comment by sre** [comment]
For the userspace side of things there are two sensible options:

1. check sysfs files exposed by the subsystem
2. make upower part of the test and use its DBus interface

I suppose the second option would be the more interesting test, since it makes sure the most common userspace application detects the device and gets correct values. OTOH that's no longer purely testing the kernel and adds extra dependencies.
