### ISSUE TITLE
Add clang-14 Docker image

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#933]
The latest released version of [LLVM/Clang](https://llvm.org) is 13.0.  However, it's already possible to install `.deb` packages from the development version for LLVM 14.  We should add support for that by defining a `clang-14` build environment, and use it initially on [staging](staging.kernelci.org) with linux-next as well as [production](https://linux.kernelci.org) for the Android common kernel.

## Implementation

* Add a Dockerfile in [config/docker/clang-14](https://github.com/kernelci/kernelci-core/tree/main/config/docker)
* Build the image locally and check that it has the correct version of LLVM/Clang installed
* Make a pull request to add this Dockerfile

## Completion

* Wait for the pull request to be deployed automatically on [staging.kernelci.org](https://staging.kernelci.org)
* Wait for the `kernelci/staging-clang-14` Docker image to become available in the Docker hub
* Get the PR reviewed and merged

**Comment by musamaanjum** [comment]
[x] Install LLVM 13 and 14
[x] Build linux-next with llvm-14
[x] Build android common kernel (chosen android13-5.15 branch which is latest in kernelci-core/config/core/build-configs-android.yaml)
  [x] Build with llvm-13
  [x] Build with llvm-14

**Building android13-5.15 with llvm-14:**
[x] defconfig, allmodconfig - Found 2 types of problems:
1. https://github.com/ClangBuiltLinux/linux/issues/1473. It has been fixed. The fix is present in linux-next (2e705706), but not in v5.15-rc6.
2. https://github.com/ClangBuiltLinux/linux/issues/1497. Fixes of these bugs haven't reached to linux-next and mainline.
[x] gki_config for x86_64 - No error
[x] gki_config for arm64

**Building android13-5.10 with llvm-14:**
[x] gki_config for x86_64
[x] gki_config for arm64

**Building android_mainline with llvm-14:**
[x] gki_config for x86_64
[x] gki_config for arm64

**Docker Images and new llvm-14 image**
[x] Build docker image for llvm-11
[x] Build docker image for llvm-12
[x] Build docker image for llvm-13
[x] Add support for llvm-14
[x]  generate docker image for llvm-14 
[x]  test docker image for llvm-14
